#!/bin/bash

log_file="/tmp/script_log.txt"

log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$log_file"
}

disable_wake_up() {
    if grep "GPP0" /proc/acpi/wakeup | grep "*enabled" >/dev/null ; then
        log_message "Disabling wake-up for device GPP0"
        echo "GPP0" > /proc/acpi/wakeup
    else
        log_message "Wake-up for device GPP0 already disabled"
    fi
}

case "$1/$2" in
    pre/*)
        log_message "Going to $2 state"
        ;;
    post/*)
        log_message "Waking up from $2 state"
        disable_wake_up
        ;;
esac
